#!/usr/bin/env python3
"""
Music Mailer — Daily music newsletter generated by Claude with live web search.
Covers: music theory, new releases, Spotify/YouTube Music/Apple Music updates, hi-fi audio news.
"""

import anthropic
import smtplib
import os
import sys
import json
import re
import html
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from dotenv import load_dotenv

_HERE = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(_HERE, ".env"), encoding="utf-8", override=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(os.path.join(os.path.dirname(__file__), "music_mailer.log"), encoding="utf-8"),
    ],
)
log = logging.getLogger(__name__)

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
SMTP_HOST        = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT        = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER        = os.getenv("SMTP_USER")
SMTP_PASSWORD    = os.getenv("SMTP_PASSWORD")
RECIPIENT_EMAIL  = os.getenv("RECIPIENT_EMAIL")
SENDER_NAME      = os.getenv("SENDER_NAME", "Music Daily")


# ---------------------------------------------------------------------------
# Step 1: Generate newsletter content via Claude + web search
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a music newsletter curator who loves both Western and Indian music.
Your reader:

- Loves music and actively experiments with music-making in Ableton Live
- Does NOT have advanced music theory training — keep explanations simple,
  emotional, and jargon-free. No technical terms without a plain-English
  explanation right next to them.
- Has a deep love for Indian film music (Bollywood, classic Hindi cinema)
  and appreciates knowing things like "this song is based on Raga Bhairavi,
  which is why it feels so bittersweet" — but does not want deep classical
  theory on ragas.
- Also enjoys Western popular music, jazz, and world music
- Subscribes to Spotify, YouTube Music, and Apple Music
- Owns hi-fi equipment and cares about lossless/high-resolution audio quality

Keep everything accessible, warm, and curiosity-driven. The goal is
to help the reader feel and understand music, not study it."""


def generate_newsletter_content() -> dict:
    """Call Claude with web_search to research and compile the newsletter."""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    today  = datetime.now().strftime("%A, %B %d, %Y")

    prompt = f"""Today is {today}. Use web search to research current information, then compile
a daily music digest with these five sections.

━━━ SECTION 1 — MUSIC SPOTLIGHT ━━━
Pick one interesting musical idea — it could be from Western music OR Indian
film music (Bollywood, classic Hindi cinema). Focus on the feeling it creates
and why. Good angles: why a particular Bollywood song feels so nostalgic, what
makes a chord progression sound cinematic, how a certain rhythm makes you want
to move, why a raga is used for a particular emotion in a famous film song.
Keep it conversational — no jargon. If you mention a raga, just describe what
it feels like, not its technical structure. Include a specific song example
(could be Bollywood or Western).

━━━ SECTION 2 — ABLETON TIP OF THE DAY ━━━
Share one practical, actionable tip for Ableton Live. Focus on hidden features
or shortcuts most people don't know, workflow tricks that save time, best
practices for arrangement/mixing/sound design, or creative techniques.
Keep it hands-on — something the reader can try today.

━━━ SECTION 3 — NEW RELEASES & MUSIC NEWS ━━━
Search for the most interesting music releases and news from the past 24-48 hours.
Include 3-4 items. Mix Western and Indian/Bollywood where relevant.

━━━ SECTION 4 — SERVICE UPDATES ━━━
Search for any recent news, feature launches, or notable updates for:
Spotify, YouTube Music, Apple Music.
Include 2-3 items across these services.

━━━ SECTION 5 — HI-FI CORNER ━━━
Search for the latest in lossless audio streaming, hi-res music releases,
Dolby Atmos / spatial audio news, or audio hardware relevant to home listeners.
Include 2-3 items.

Return ONLY a valid JSON object — no markdown fences, no preamble, no extra text.
Use this exact structure:

{{
  "music_spotlight": {{
    "title": "short catchy title (5-8 words)",
    "mood": "one word or short phrase describing the feeling/emotion",
    "explanation": "2-3 paragraphs separated by two newlines — conversational, jargon-free",
    "song_example": "Artist - Song Title: one sentence on why this song is the perfect example",
    "raga_note": "ONLY include if the example is Indian music — one casual sentence like This song is based on Raga X, which is the raga of... — omit this field entirely for Western examples"
  }},
  "ableton_tip": {{
    "title": "short title for the tip",
    "tip": "the practical tip or trick, 2-4 sentences",
    "why_useful": "one sentence on why this saves time or improves your music"
  }},
  "music_news": [
    {{"headline": "...", "summary": "1-2 sentences", "source": "publication name"}}
  ],
  "service_updates": [
    {{"service": "Spotify | YouTube Music | Apple Music", "headline": "...", "details": "1-2 sentences"}}
  ],
  "hifi_corner": [
    {{"title": "...", "summary": "1-2 sentences", "why_it_matters": "one sentence for a lossless-audio listener"}}
  ]
}}"""

    messages = [{"role": "user", "content": prompt}]
    tools    = [{"type": "web_search_20260209", "name": "web_search"}]

    max_continuations = 6
    response = None

    for attempt in range(max_continuations):
        log.info("Calling Claude API (attempt %d)…", attempt + 1)
        response = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=8000,
            system=SYSTEM_PROMPT,
            thinking={"type": "adaptive"},
            tools=tools,
            messages=messages,
        )

        if response.stop_reason == "end_turn":
            log.info("Claude finished.")
            break
        elif response.stop_reason == "pause_turn":
            # Server-side tool loop hit its iteration limit — resume
            log.info("Claude paused (server tool limit); resuming…")
            messages = [
                {"role": "user",      "content": prompt},
                {"role": "assistant", "content": response.content},
            ]
        else:
            log.warning("Unexpected stop_reason: %s", response.stop_reason)
            break

    if response is None:
        raise RuntimeError("No response received from Claude API")

    raw_text = _extract_text(response)
    log.info("Parsing JSON from Claude's response…")
    return _parse_json(raw_text)


def _extract_text(response) -> str:
    """Return the last text block from a response (skips thinking / tool blocks)."""
    text_blocks = [b for b in response.content if getattr(b, "type", None) == "text"]
    if not text_blocks:
        raise ValueError("Claude returned no text block")
    return text_blocks[-1].text


def _parse_json(text: str) -> dict:
    """Robustly extract a JSON object from Claude's response."""
    text = text.strip()

    # 1. Direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # 2. JSON inside ```json … ``` fences
    m = re.search(r"```json\s*(.*?)\s*```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass

    # 3. Find the outermost { … }
    start = text.find("{")
    end   = text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            pass

    raise ValueError("Could not parse JSON from Claude's response.\nRaw text:\n" + text[:500])


# ---------------------------------------------------------------------------
# Step 2: Build the HTML email
# ---------------------------------------------------------------------------

SERVICE_COLORS = {
    "Spotify":       "#1DB954",
    "YouTube Music": "#FF0000",
    "Apple Music":   "#FC3C44",
}


def _e(text: str) -> str:
    """HTML-escape a string for safe embedding."""
    return html.escape(str(text or ""), quote=False)


def _paragraphs(text: str) -> str:
    """Convert double-newline-separated paragraphs into <p> tags."""
    parts = [p.strip() for p in str(text or "").split("\n\n") if p.strip()]
    return "".join(
        f'<p style="margin:0 0 12px;font-size:15px;line-height:1.75;color:#374151;">{_e(p)}</p>'
        for p in parts
    )


def build_html_email(data: dict) -> str:
    today    = datetime.now().strftime("%A, %B %d, %Y")
    spotlight = data.get("music_spotlight", {})
    ableton  = data.get("ableton_tip", {})
    news     = data.get("music_news", [])
    updates  = data.get("service_updates", [])
    hifi     = data.get("hifi_corner", [])

    # ── Music Spotlight section ──────────────────────────────────────────────
    raga_note_html = ""
    if spotlight.get("raga_note"):
        raga_note_html = f"""
      <div style="background:#fff7ed;border-radius:8px;padding:14px 16px;
                  margin:12px 0;border-left:4px solid #f59e0b;">
        <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#d97706;
                  text-transform:uppercase;letter-spacing:0.5px;">🪗 Raga note</p>
        <p style="margin:0;font-size:14px;color:#1f2937;">{_e(spotlight.get('raga_note', ''))}</p>
      </div>"""

    spotlight_html = f"""
    <div style="background:linear-gradient(135deg,#eef2ff 0%,#f0f9ff 100%);
                border-radius:12px;padding:24px 28px;">
      <h3 style="margin:0 0 4px;font-size:22px;font-weight:800;color:#1e1b4b;">
        {_e(spotlight.get('title', ''))}
      </h3>
      <p style="margin:0 0 18px;font-size:14px;color:#6366f1;font-weight:600;
                text-transform:uppercase;letter-spacing:0.5px;">
        {_e(spotlight.get('mood', ''))}
      </p>
      {_paragraphs(spotlight.get('explanation', ''))}
      <div style="background:#fff;border-radius:8px;padding:14px 16px;
                  margin:16px 0 12px;border-left:4px solid #6366f1;">
        <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#4f46e5;
                  text-transform:uppercase;letter-spacing:0.5px;">🎵 Listen to</p>
        <p style="margin:0;font-size:14px;color:#1f2937;">{_e(spotlight.get('song_example', ''))}</p>
      </div>
      {raga_note_html}
    </div>"""

    # ── Ableton Tip section ──────────────────────────────────────────────────
    ableton_html = f"""
    <div style="background:linear-gradient(135deg,#f0fdf4 0%,#ecfdf5 100%);
                border-radius:12px;padding:24px 28px;">
      <h3 style="margin:0 0 16px;font-size:18px;font-weight:800;color:#14532d;">
        🎛️ {_e(ableton.get('title', ''))}
      </h3>
      {_paragraphs(ableton.get('tip', ''))}
      <div style="background:#fff;border-radius:8px;padding:12px 16px;
                  border-left:4px solid #10b981;margin-top:12px;">
        <p style="margin:0;font-size:13px;color:#065f46;font-style:italic;">
          {_e(ableton.get('why_useful', ''))}
        </p>
      </div>
    </div>"""

    # ── News items ───────────────────────────────────────────────────────────
    news_items = ""
    for item in news:
        news_items += f"""
        <div style="border-bottom:1px solid #e5e7eb;padding:14px 0;">
          <p style="margin:0;font-size:15px;font-weight:600;color:#1f2937;">
            {_e(item.get('headline', ''))}
          </p>
          <p style="margin:5px 0 4px;font-size:14px;line-height:1.6;color:#4b5563;">
            {_e(item.get('summary', ''))}
          </p>
          <p style="margin:0;font-size:12px;color:#9ca3af;">{_e(item.get('source', ''))}</p>
        </div>"""

    # ── Service update items ─────────────────────────────────────────────────
    service_items = ""
    for item in updates:
        svc   = item.get("service", "")
        color = SERVICE_COLORS.get(svc, "#6b7280")
        service_items += f"""
        <div style="border-left:3px solid {color};padding:10px 16px;margin:12px 0;
                    background:#f9fafb;border-radius:0 8px 8px 0;">
          <span style="font-size:11px;font-weight:700;color:{color};
                       text-transform:uppercase;letter-spacing:0.5px;">{_e(svc)}</span>
          <p style="margin:5px 0 3px;font-size:15px;font-weight:600;color:#1f2937;">
            {_e(item.get('headline', ''))}
          </p>
          <p style="margin:0;font-size:14px;line-height:1.6;color:#4b5563;">
            {_e(item.get('details', ''))}
          </p>
        </div>"""

    # ── Hi-Fi items ──────────────────────────────────────────────────────────
    hifi_items = ""
    for item in hifi:
        hifi_items += f"""
        <div style="background:#f3f4f6;border-radius:8px;padding:14px 18px;margin:10px 0;">
          <p style="margin:0 0 6px;font-size:15px;font-weight:600;color:#1f2937;">
            🎧 {_e(item.get('title', ''))}
          </p>
          <p style="margin:0 0 6px;font-size:14px;line-height:1.6;color:#4b5563;">
            {_e(item.get('summary', ''))}
          </p>
          <p style="margin:0;font-size:13px;color:#6b7280;font-style:italic;">
            Why it matters: {_e(item.get('why_it_matters', ''))}
          </p>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>🎵 Music Daily — {_e(today)}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;
             font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;">

  <div style="max-width:640px;margin:24px auto;background:#fff;
              border-radius:16px;overflow:hidden;
              box-shadow:0 4px 24px rgba(0,0,0,0.08);">

    <!-- ── Header ── -->
    <div style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 55%,#0f3460 100%);
                padding:36px 32px 30px;text-align:center;">
      <div style="font-size:40px;margin-bottom:10px;">🎵</div>
      <h1 style="margin:0;font-size:30px;font-weight:800;color:#fff;letter-spacing:-0.5px;">
        Music Daily
      </h1>
      <p style="margin:8px 0 0;font-size:14px;color:#94a3b8;">{_e(today)}</p>
    </div>

    <!-- ── Body ── -->
    <div style="padding:0 32px 40px;">

      <!-- Music Spotlight -->
      <div style="margin-top:32px;">
        <div style="display:flex;align-items:center;margin-bottom:14px;">
          <span style="font-size:20px;margin-right:10px;">🎼</span>
          <h2 style="margin:0;font-size:12px;font-weight:800;color:#6366f1;
                     text-transform:uppercase;letter-spacing:1.2px;">
            Music Spotlight
          </h2>
        </div>
        {spotlight_html}
      </div>

      <!-- Ableton Tip of the Day -->
      <div style="margin-top:32px;">
        <div style="display:flex;align-items:center;margin-bottom:14px;">
          <span style="font-size:20px;margin-right:10px;">🎛️</span>
          <h2 style="margin:0;font-size:12px;font-weight:800;color:#10b981;
                     text-transform:uppercase;letter-spacing:1.2px;">
            Ableton Tip of the Day
          </h2>
        </div>
        {ableton_html}
      </div>

      <!-- New Releases & Music News -->
      <div style="margin-top:32px;">
        <div style="display:flex;align-items:center;margin-bottom:14px;">
          <span style="font-size:20px;margin-right:10px;">📰</span>
          <h2 style="margin:0;font-size:12px;font-weight:800;color:#f59e0b;
                     text-transform:uppercase;letter-spacing:1.2px;">
            New Releases &amp; Music News
          </h2>
        </div>
        <div style="border:1px solid #e5e7eb;border-radius:12px;padding:4px 20px;">
          {news_items}
        </div>
      </div>

      <!-- Service Updates -->
      <div style="margin-top:32px;">
        <div style="display:flex;align-items:center;margin-bottom:14px;">
          <span style="font-size:20px;margin-right:10px;">📱</span>
          <h2 style="margin:0;font-size:12px;font-weight:800;color:#10b981;
                     text-transform:uppercase;letter-spacing:1.2px;">
            Service Updates
          </h2>
        </div>
        {service_items}
      </div>

      <!-- Hi-Fi Corner -->
      <div style="margin-top:32px;">
        <div style="display:flex;align-items:center;margin-bottom:14px;">
          <span style="font-size:20px;margin-right:10px;">🔊</span>
          <h2 style="margin:0;font-size:12px;font-weight:800;color:#ef4444;
                     text-transform:uppercase;letter-spacing:1.2px;">
            Hi-Fi Corner
          </h2>
        </div>
        {hifi_items}
      </div>

    </div>

    <!-- ── Footer ── -->
    <div style="background:#f9fafb;border-top:1px solid #e5e7eb;
                padding:20px 32px;text-align:center;">
      <p style="margin:0;font-size:12px;color:#9ca3af;">
        Generated daily by Claude · Music Daily Newsletter
      </p>
      <p style="margin:6px 0 0;font-size:11px;color:#d1d5db;">
        Powered by Anthropic Claude with live web search
      </p>
    </div>

  </div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Step 3: Send the email
# ---------------------------------------------------------------------------

def send_email(html_content: str, subject: str) -> None:
    msg            = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"{SENDER_NAME} <{SMTP_USER}>"
    msg["To"]      = RECIPIENT_EMAIL

    # Plain-text fallback
    plain = f"{subject}\n\nOpen this email in an HTML-capable client to view the newsletter."
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_content, "html", "utf-8"))

    log.info("Connecting to %s:%s…", SMTP_HOST, SMTP_PORT)
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_USER, RECIPIENT_EMAIL, msg.as_string())

    log.info("✓ Email sent to %s", RECIPIENT_EMAIL)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _check_config() -> list[str]:
    required = ["ANTHROPIC_API_KEY", "SMTP_USER", "SMTP_PASSWORD", "RECIPIENT_EMAIL"]
    return [k for k in required if not os.getenv(k)]


def main() -> int:
    test_mode = "--test" in sys.argv   # print HTML to stdout, don't send

    log.info("═" * 60)
    log.info("Music Mailer starting%s", " (TEST MODE)" if test_mode else "")

    missing = _check_config()
    if missing:
        log.error("Missing required env vars: %s", ", ".join(missing))
        log.error("Copy .env.example → .env and fill in your values.")
        return 1

    try:
        log.info("Generating newsletter via Claude + web search…")
        data = generate_newsletter_content()

        log.info("Building HTML email…")
        html_content = build_html_email(data)

        today   = datetime.now().strftime("%B %d, %Y")
        subject = f"🎵 Music Daily — {today}"

        if test_mode:
            print(html_content)
            log.info("Test mode: HTML written to stdout. Not sending email.")
        else:
            send_email(html_content, subject)

        log.info("Done.")
        return 0

    except Exception:
        log.exception("Newsletter failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
